# 二、马尔可夫链
+ 在蒙特卡罗方法中，我们讲到了如何用蒙特卡罗方法来随机模拟求解一些复杂的连续积分或者离散求和的方法，但是这个方法需要得到对应的概率分布的样本集，而想得到这样的样本集很困难。因此我们需要本篇讲到的马尔科夫链来帮忙。

## 1. 马尔科夫链概述
+ 马尔科夫链定义本身比较简单，它假设某一时刻状态转移的概率只依赖于它的前一个状态。
+ 举个形象的比喻，假如每天的天气是一个状态的话，那个今天是不是晴天只依赖于昨天的天气，而和前天的天气没有任何关系。
+ 如果用精确的数学定义来描述，则假设我们的序列状态是$...𝑋_{t−2},𝑋_{t−1},𝑋_t,𝑋_{t+1},...，$那么我们在时刻$𝑋_{t+1}$的状态的条件概率仅仅依赖于时刻$𝑋_t$，即：
$$𝑃(𝑋_{t+1}|𝑋_t,X_{t-1},X_{t-2},...)=𝑃(𝑋_{t+1}|𝑋_t) \tag{1}$$

+ 既然某一时刻状态转移的概率只依赖于它的前一个状态，那么我们只要能求出系统中任意两个状态之间的转换概率，这个马尔科夫链的模型就定了。
+ 例如马尔可夫链表示的股市模型：
<div align="center"> <img src="media/mc3.png" width="50%" /> </div>

+ 对应的状态转移矩阵为：
$$p = \begin{bmatrix}
0.9 & 0.075 & 0.025 \\
0.15 & 0.8 & 0.05 \\
0.25 & 0.25 & 0.5 \\
\end{bmatrix}$$

## 2. 马尔科夫链模型状态转移矩阵的性质
+ 假设我们当前股市的概率分布为：[0.3,0.4,0.3],即30%概率的牛市，40%概率的熊盘与30%的横盘。然后这个状态作为序列概率分布的初始状态$t_0$，将其带入这个状态转移矩阵计算$t_1,t_2,t_3,...$的状态。代码如下：

In [2]:
import numpy as np
matrix = np.matrix([[0.9,0.075,0.025],[0.15,0.8,0.05],[0.25,0.25,0.5]], dtype=float)
vector1 = np.matrix([[0.3,0.4,0.3]], dtype=float)
for i in range(100):
    vector1 = vector1*matrix
    print("Current round:" , i+1)
    print(vector1)

Current round: 1
[[0.405  0.4175 0.1775]]
Current round: 2
[[0.4715  0.40875 0.11975]]
Current round: 3
[[0.5156 0.3923 0.0921]]
Current round: 4
[[0.54591  0.375535 0.078555]]
Current round: 5
[[0.567288 0.36101  0.071702]]
Current round: 6
[[0.5826362 0.3492801 0.0680837]]
Current round: 7
[[0.59378552 0.34014272 0.06607176]]
Current round: 8
[[0.60194632 0.33316603 0.06488765]]
Current round: 9
[[0.6079485  0.32790071 0.06415079]]
Current round: 10
[[0.61237646 0.3239544  0.06366914]]
Current round: 11
[[0.61564926 0.32100904 0.0633417 ]]
Current round: 12
[[0.61807111 0.31881635 0.06311253]]
Current round: 13
[[0.61986459 0.31718655 0.06294886]]
Current round: 14
[[0.62119333 0.3159763  0.06283037]]
Current round: 15
[[0.62217803 0.31507813 0.06274383]]
Current round: 16
[[0.62290791 0.31441182 0.06268027]]
Current round: 17
[[0.62344896 0.31391762 0.06263343]]
Current round: 18
[[0.62385006 0.31355112 0.06259882]]
Current round: 19
[[0.62414743 0.31327936 0.06257322]]
Current roun

+ 可以发现，从第60轮开始，我们的状态概率分布就不变了，一直保持在[0.625   0.3125  0.0625]，即62.5%的牛市，31.25%的熊市与6.25%的横盘。那么这个是巧合吗？
+ 我们现在换一个初始概率分布试一试，现在我们用[0.7,0.1,0.2]作为初始概率分布，然后这个状态作为序列概率分布的初始状态$t_0$，将其带入这个状态转移矩阵计算$t_1,t_2,t_3,...$的状态。代码如下：

In [3]:
matrix = np.matrix([[0.9,0.075,0.025],[0.15,0.8,0.05],[0.25,0.25,0.5]], dtype=float)
vector1 = np.matrix([[0.7,0.1,0.2]], dtype=float)
for i in range(100):
    vector1 = vector1*matrix
    print("Current round:" , i+1)
    print(vector1)

Current round: 1
[[0.695  0.1825 0.1225]]
Current round: 2
[[0.6835  0.22875 0.08775]]
Current round: 3
[[0.6714 0.2562 0.0724]]
Current round: 4
[[0.66079  0.273415 0.065795]]
Current round: 5
[[0.652172 0.28474  0.063088]]
Current round: 6
[[0.6454378 0.2924769 0.0620853]]
Current round: 7
[[0.64028688 0.29791068 0.06180244]]
Current round: 8
[[0.6363954  0.30180067 0.06180393]]
Current round: 9
[[0.63347695 0.30462117 0.06190188]]
Current round: 10
[[0.6312979  0.30668318 0.06201892]]
Current round: 11
[[0.62967532 0.30819862 0.06212607]]
Current round: 12
[[0.62846909 0.30931606 0.06221485]]
Current round: 13
[[0.6275733  0.31014174 0.06228495]]
Current round: 14
[[0.62690847 0.31075263 0.0623389 ]]
Current round: 15
[[0.62641525 0.31120496 0.06237979]]
Current round: 16
[[0.62604941 0.31154006 0.06241053]]
Current round: 17
[[0.62577811 0.31178839 0.0624335 ]]
Current round: 18
[[0.62557693 0.31197244 0.06245062]]
Current round: 19
[[0.62542776 0.31210888 0.06246336]]
Current roun

+ 可以看出，尽管这次我们采用了不同初始概率分布，最终状态的概率分布趋于同一个稳定的概率分布[0.625   0.3125  0.0625]， 也就是说我们的马尔科夫链模型的状态转移矩阵收敛到的稳定概率分布与我们的初始状态概率分布无关。这是一个非常好的性质，也就是说，如果我们得到了这个稳定概率分布对应的马尔科夫链模型的状态转移矩阵，则我们可以用任意的概率分布样本开始，带入马尔科夫链模型的状态转移矩阵，这样经过一些序列的转换，最终就可以得到符合对应稳定概率分布的样本。
+ 这个性质不光对我们上面的状态转移矩阵有效，对于绝大多数的其他的马尔科夫链模型的状态转移矩阵也有效。同时不光是离散状态，连续状态时也成立。
+ 同时，对于一个确定的状态转移矩阵𝑃，它的n次幂$p^n$在当n大于一定的值的时候也可以发现是确定的，我们还是以上面的例子为例，计算代码如下：

In [4]:
matrix = np.matrix([[0.9,0.075,0.025],[0.15,0.8,0.05],[0.25,0.25,0.5]],dtype=float)
for i in range(10):
    matrix *= matrix
    print("Current round:", i+1)
    print(matrix)

Current round: 1
[[0.8275  0.13375 0.03875]
 [0.2675  0.66375 0.06875]
 [0.3875  0.34375 0.26875]]
Current round: 2
[[0.73555  0.212775 0.051675]
 [0.42555  0.499975 0.074475]
 [0.51675  0.372375 0.110875]]
Current round: 3
[[0.65828326 0.28213131 0.05958543]
 [0.56426262 0.36825403 0.06748335]
 [0.5958543  0.33741675 0.06672895]]
Current round: 4
[[0.62803724 0.30972343 0.06223933]
 [0.61944687 0.3175772  0.06297594]
 [0.6223933  0.3148797  0.062727  ]]
Current round: 5
[[0.62502532 0.31247685 0.06249783]
 [0.6249537  0.31254233 0.06250397]
 [0.62497828 0.31251986 0.06250186]]
Current round: 6
[[0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]]
Current round: 7
[[0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]]
Current round: 8
[[0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]]
Current round: 9
[[0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]
 [0.625  0.3125 0.0625]]
Current round: 10
[[0.625  0.3125 0.0625]
 [0.625  0.31

+ 我们可以发现，在𝑛≥6以后，𝑃𝑛的值稳定不再变化，而且每一行都为[0.625 0.3125 0.0625]，这和我们前面的稳定分布是一致的。这个性质同样不光是离散状态，连续状态时也成立。
+ 好了，现在我们可以用数学语言总结下马尔科夫链的收敛性质了：
+ 如果一个非周期的马尔科夫链有状态转移矩阵𝑃, 并且它的任何两个状态是连通的，那么$\displaystyle\lim_{n \to \infty}p_{ij}^n$与i无关，我们有：
$$\displaystyle\lim_{n \to \infty}p_{ij}^n=\pi(j) \tag{2}$$
$$\displaystyle\lim_{n \to \infty}p^n=
\begin{bmatrix} 
\pi(1) & \pi(2) & \ldots & \pi(j) & \ldots \\
\pi(1) & \pi(2) & \ldots & \pi(j) & \ldots \\
\ldots & \ldots & \ldots & \ldots & \ldots \\
\pi(1) & \pi(2) & \ldots & \pi(j) & \ldots \\
\ldots & \ldots & \ldots & \ldots & \ldots \\
\end{bmatrix}
\tag{3}$$
$$\pi(j)=\sum_{i=0}^{\infty}\pi(i)p_{ij} \tag{4}$$
+ $\pi$是$\pi P = \pi$的唯一非负解，其中：
$$\pi = [\pi(1),\pi(2),\cdots,\pi(j),\cdots],\sum_{i=0}^{\infty}\pi(i)=1 \tag{5}$$


## 3. 基于马尔可夫链采样
+ 如果我们得到了某个平稳分布所对应的马尔科夫链状态转移矩阵，我们就很容易采用出这个平稳分布的样本集。

+ 假设我们任意初始的概率分布是$\pi_0(x)$, 经过第一轮马尔科夫链状态转移后的概率分布是$\pi_1(x)$，第i轮的概率分布是$\pi_i(x)$。假设经过n轮后马尔科夫链收敛到我们的平稳分布$\pi(x)$，即：
$$\pi_n(x)=\pi_{n+1}(x)=\pi_{n+2}(x)=\ldots=\pi(x)$$

+ 对于每个分布$\pi_i(x)$，有：
$$\pi_i(x)=\pi_{i-1}(x)P=\pi_{i-2}(x)P^2=\ldots=\pi_0(x)P^i$$

+ 现在我们可以开始采样了，首先，基于初始任意简单概率分布比如高斯分布$\pi_0(x)$采样得到状态值$x_0$，基于条件概率分布$p(x|x_0)$采样状态值$x_1$，一直进行下去，当状态转移进行到一定的次数时，比如到n次时，我们认为此时的采样集($x_n,x_{n+1},x_{n+2},\ldots$)即是符合我们的平稳分布的对应样本集，可以用来做蒙特卡罗模拟求和了。
+ 总结下基于马尔科夫链的采样过程：
  + 1. 输入马尔科夫链状态转移矩阵𝑃，设定状态转移次数阈值$n_1$，需要的样本个数$n_2$;
  + 2. 从任意简单概率分布采样得到初始状态值$x_0$;
  + 3. for 𝑡=0 to $n_1+n_2-1$: 从条件概率分布$p(x|x_t)$中采样得到样本$x_{t+1}$;
+ 样本集($x_{n_1},x_{n_1+1},\ldots,x_{n_1+n_2-1}$)即为我们需要的平稳分布对应的样本集。

## 4. 马尔科夫链采样小结
+ 如果假定我们可以得到我们需要采样样本的平稳分布所对应的马尔科夫链状态转移矩阵，那么我们就可以用马尔科夫链采样得到我们需要的样本集，进而进行蒙特卡罗模拟。但是一个重要的问题是，随意给定一个平稳分布𝜋,如何得到它所对应的马尔科夫链状态转移矩阵𝑃呢？这是个大问题。我们绕了一圈似乎还是没有解决任意概率分布采样样本集的问题。
+ 幸运的是，MCMC采样通过迂回的方式解决了上面这个大问题，我们在下一篇来讨论MCMC的采样，以及它的使用改进版采样: M-H采样和Gibbs采样.