setwd("E:/Codelearning/fastSOM")
library("vars")
data(Canada)
var.2c<-VAR(Canada,p=2,type = "const")
Acoef(var.2c)
var.2c.prd<-predict(var.2c,n.ahead = 8,ci=0.95)
fanchart(var.2c.prd)
var.2c.fevd<-fevd(var.2c,n.ahead = 5)
fitted(var.2c)
irf(var.2c, impulse = "e", response = c("prod", "rw", "U"), boot =FALSE)
amat <- diag(4)
diag(amat) <- NA
svar.a <- SVAR(var.2c, estmethod = "direct", Amat = amat)
irf(svar.a, impulse = "e", response = c("prod", "rw", "U"), boot =FALSE)
logLik(var.2c)
normality.test(var.2c)
Phi(var.2c, nstep=4)
plot(var.2c)
archtest <- arch.test(var.2c)
plot(archtest)
var.2c.fevd <- fevd(var.2c, n.ahead = 5)
plot(var.2c.fevd)
var.2c.irf <- irf(var.2c, impulse = "e",response = c("prod", "rw", "U"), boot = FALSE)
plot(var.2c.irf)
var.2c.prd <- predict(var.2c, n.ahead = 8, ci = 0.95)
plot(var.2c.prd)
var.2c.stabil <- stability(var.2c, type = "Rec-CUSUM")
plot(var.2c.stabil)
Psi(var.2c, nstep=4)
roots(var.2c)
